### ISSUE TITLE
Create the playspace

### ISSUE THREAD

**Issue by ldallos** [ldallos/evoLudo#2]
- [x] Create squares
- [x] Fill the playspace with squares

Total: 4 h

**Comment by aronnagy** [comment]
I've got some troubles with the squares. I can create them (in a different class and also in a the Board class), but I am unable to fill up the play-space with them because It's somehow override the Board what Kriszitán created.

**Comment by ldallos** [comment]
How would you like to add the squares?
Can you send me a sample code?

**Comment by aronnagy** [comment]
public void paint(Graphics g) {

        g.drawRect(200,200,400,400);

    }

This is my basic method for one square. I wanted to write a similar method in initBoard()
for example: initBoard(Graphichs g) { ...
But It's not working like that.

**Comment by ldallos** [comment]
You have to call the paint method of the parent class. For example:
`public void paint(Graphics g) {
        super.paint(g);
        g.drawRect(200,200,400,400);
}`

**Comment by aronnagy** [comment]
I've done with the routes. Somehow the middle color module redraw the squares. It was not happening until I've done the dynamic size changing so probably this caused the problem. I'll done with it ASAP.
plus: Somehow the whole playspace slides up a bit (I don't know why because the value of the positions must be correct (it was taken from Krisztián's method))

**Comment by ldallos** [comment]
The playspace slides issue has been solved with the Krisztián's change set.
