### ISSUE TITLE
Create the steps

### ISSUE THREAD

**Issue by ldallos** [ldallos/evoLudo#6]
- [x] Steps from square to square
- [x] Steps from player's yard to starting square

Total: 4-10 h

**Comment by aronnagy** [comment]
Hi!

My main idea is that we should save the positions of the different figures. (I was thinking in four different arrays first, but I realized that is unnecessary because on a position it can be one figure only)
So we'll get one array (String variable, 56 size).
The code and the values will looks like this:

_Route[0] =  "redStart";
Route[14] = "blueStart";
//...
for(int i = 1; i  < 14 ; i++)
{
   Route[i] = "redRoute" + i; 
}
//..._

After these basic steps comes the hard part...

**1st**: _Somehow we have to assign these array values for positions, where we'll draw the figures.
(Based on Route Squares)_
**2nd:** _We have to save the actual positions of the figures. We can save it directly into the array or create an another array just for the positions  (I am actually not sure about that yet...)_
**3rd:** _Create the figures themselves._

I would left the animation later.
I start to implement this idea today, but if there any problem just tell me and I'll think the whole problem
again.

Have a nice day! 
Aron

**Comment by ldallos** [comment]
> **2nd:** We have to save the actual positions of the figures. We can save it directly into the array or create an another array just for the positions (I am actually not sure about that yet...)

You can save the positions of the figures into the string array (for example: "yellowRoute5|greenToken1") or into another array.

**But the best way**: you should create a new position class for that with the following attributes:
_String positionFunction = "redStart"; (or for example: redRoute)
String currentToken = "green1"; (or null)_

And you should add this position objects to the array.

**Comment by ldallos** [comment]
> **1st:** _Somehow we have to assign these array values for positions, where we'll draw the figures.
(Based on Route Squares)_

You are drawing currently the squares with a two dimensional method (with 2 _'for iteration'_).
So you could save the positions in a two dimensional array (matrix) instead of one dimensional array.
Or you should try to transform the two coordinates from the MyContainingJPanel to one array index.

> **3rd:** _Create the figures themselves._

A simple circle will be good for first time.

**Comment by ilkukrisz** [comment]
Hi! Unfortunately I have gone into some problems. I don't know what causes the error, but i need some help to fix it, if you got the same error. Maybe it problem raises only because of the intellij IDEA tool. Please try to run the code in your computers, and if there is any problem there, notify me about it. The error message that i got:

"Process finished with exit code 130 (interrupted by signal 2: SIGINT)"

Thanks in advance

**Comment by ldallos** [comment]
You have made a StackOverflowError in your code. 
The reason of that the following circular dependency:
If a MyContainingJPanel object is created then it would create a Route object. But the Route object would create another MyContainingJPanel object, etc.

**Comment by ilkukrisz** [comment]
Now the half of the issue if finished. Step from square to square is now possible. It is going to be seen when Áron finishes the drawing. Now controller is free from static methods, and working everything. The next minor improvement on the token selector window is that is dissappears, when we click on one of our own buttons. At the time of commenting, it is working that way, we press the token button we want to select, and the "OK" button to let it go. Please check my code wether you can find any problems of mistakes in it. Thanks in advance!!

**Comment by ldallos** [comment]
That seems to be OK.
My UI glitch has been solved also with the JOptionPane instead of a new JFrame.

**Comment by ilkukrisz** [comment]
Thank you. Now only the painting needed, which will be done by Áron. I can go on and continue to develop the logic to handling two token at the same square, and to manipulate available buttons in the selector menu to show only the available tokens' button. But it would be the task of the next issue. So after we merge this branch, I can work on that in an other branch.

**Comment by ldallos** [comment]
I have found a small bug in the token number drawing.
The fourth y coordinate is the third in the follwing colors: blue, green, yellow.
Maybe it is a copy+paste failure.

**Comment by ilkukrisz** [comment]
Yes, I also found that. In the upcoming commit this will be fixed.

**Comment by aronnagy** [comment]
Hi Guys,
I checked the game (as I agreed with Krisztián). Here's a small report about the bugs what I founded.

If a friendly token already placed on starting field and I dice 6 I have the possibility to put down an another friendly token. But nothing will happens, the game just jump to the next player.
By the rules, It is correct because you cannot place 2 friendly tokens on the stating fields. We must fix like this: Do not let the player pick a token from home field until the starting field is free again.

According to that question. What happens if I dice 6 again and there is an enemy token on it. Will this move knock out the enemy token or It is just the same situation what I mentioned before?

And finally, the end of the game. We talked about it that won't be enough space in the middle for the tokens. So we are just draw out a number. Am I right?

That's all for now. I will think about these problems I just wanted to inform you too.
Have nice weekend!

**Comment by ldallos** [comment]
> According to that question. What happens if I dice 6 again and there is an enemy token on it. Will this move knock out the enemy token or It is just the same situation what I mentioned before?

You can knock out the enemy token.


> And finally, the end of the game. We talked about it that won't be enough space in the middle for the tokens. So we are just draw out a number. Am I right?

 Yes, you can draw a number.

**Comment by ldallos** [comment]
The tasks have been finished. So I have closed the issue.
